# Generated by Django 3.0.7 on 2020-07-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapshot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='long',
            new_name='lng',
        ),
    ]
