# Generated by Django 3.0.7 on 2020-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapshot', '0004_auto_20200721_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='details',
            field=models.IntegerField(default=None),
        ),
    ]
