# Generated by Django 3.0.7 on 2020-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapshot', '0006_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(default=None, max_length=220),
        ),
    ]
